version: "3.3"

services:
  gbans:
    build:
      context: "../"
      dockerfile: Dockerfile
    volumes:
      - dl_cache:/app/.cache
      - ./gbans.yml:/app/gbans.yml
    depends_on:
      - postgres
    networks:
      - prod_network
    ports:
      # This is generally expected to run under a reverse proxy, like Caddy.
      - "127.0.0.1:6006:6006"
    environment:
      GBANS_DATABASE_DSN: postgresql://gbans:gbans@postgres:5432/gbans
      GBANS_GENERAL_STEAM_KEY: ${GBANS_GENERAL_STEAM_KEY}
    command: ./gbans serve

  postgres:
    image: postgis/postgis:15-3.3
    restart: always
    volumes:
      - gbans_db:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_USER: gbans
      POSTGRES_DB: gbans
      POSTGRES_PASSWORD: gbans
    networks:
      - prod_network

  minio:
    # Files are currently designed to be served from
    image: docker.io/bitnami/minio:2023
    restart: always
    environment:
      # *must* be >= 8 chars or minio will not start
      - MINIO_ROOT_USER=gbansgbans
      - MINIO_ROOT_PASSWORD=gbansgbans
    ports:
      - '127.0.0.1:9000:9000'
      - '127.0.0.1:9001:9001'
    volumes:
      - 'minio_data:/bitnami/minio/data'
    networks:
      - prod_network

volumes:
  dl_cache:
  gbans_db:
  minio_data:

networks:
  prod_network:
